create table if not exists public.categories (
  id text primary key,
  name text not null check (char_length(btrim(name)) between 1 and 50),
  slug text not null unique,
  active boolean not null default true,
  sort_order integer not null default 0 check (sort_order between 0 and 9999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists categories_name_lower_unique on public.categories (lower(name));

create table if not exists public.products (
  id integer generated by default as identity primary key,
  category_id text not null references public.categories(id) on update cascade on delete restrict,
  name text not null check (char_length(btrim(name)) between 1 and 100),
  description text not null check (char_length(btrim(description)) between 1 and 400),
  price_cents integer not null check (price_cents between 1 and 100000000),
  image_url text,
  symbol text not null default '✦',
  featured boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0 check (sort_order between 0 and 9999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_public_order on public.products (sort_order, id) where active;
create index if not exists products_category_id on public.products (category_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.products enable row level security;

revoke all on public.categories, public.products from public, anon, authenticated;
grant select on public.categories, public.products to anon, authenticated;
grant insert, update on public.categories, public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

drop policy if exists categories_read_active_or_admin on public.categories;
create policy categories_read_active_or_admin
on public.categories for select to anon, authenticated
using (active or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists categories_write_admin on public.categories;
create policy categories_write_admin
on public.categories for insert to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists categories_update_admin on public.categories;
create policy categories_update_admin
on public.categories for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists products_read_active_or_admin on public.products;
create policy products_read_active_or_admin
on public.products for select to anon, authenticated
using (
  (
    active and exists (
      select 1 from public.categories c
      where c.id = products.category_id and c.active
    )
  )
  or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists products_insert_admin on public.products;
create policy products_insert_admin
on public.products for insert to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists products_update_admin on public.products;
create policy products_update_admin
on public.products for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.categories (id, name, slug, active, sort_order)
values
  ('cafes', 'Cafés', 'cafes', true, 0),
  ('bebidas', 'Bebidas', 'bebidas', true, 1),
  ('doces', 'Doces', 'doces', true, 2),
  ('salgados', 'Salgados', 'salgados', true, 3),
  ('combos', 'Combos', 'combos', true, 4)
on conflict (id) do nothing;

insert into public.products (id, category_id, name, description, price_cents, image_url, symbol, featured, active, sort_order)
values
  (1, 'cafes', 'Café Arcano', 'Café especial preparado com um toque mágico da casa.', 1290, null, '☕', true, true, 0),
  (2, 'bebidas', 'Poção Roxa', 'Bebida refrescante e misteriosa, perfeita para aventureiros.', 1590, null, '✧', true, true, 1),
  (3, 'doces', 'Bolo do Mago', 'Fatia generosa de bolo artesanal preparada na casa.', 1490, null, '✦', false, true, 2),
  (4, 'doces', 'Cookie Encantado', 'Cookie artesanal com chocolate e uma dose de magia.', 990, null, '❋', false, true, 3),
  (5, 'salgados', 'Torrada do Aventureiro', 'Torrada crocante com recheio especial da casa.', 1690, null, '❧', false, true, 4),
  (6, 'combos', 'Combo do Mago', 'Café Arcano + Cookie Encantado.', 2090, null, '♜', true, true, 5)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest(coalesce((select max(id) from public.products), 1), 1),
  exists (select 1 from public.products)
);
